version: '3'
services:
    practica-nginx:
        container_name: practica-nginx
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
            args:
                VHOST_FILE: ${VHOST_FILE}
        volumes:
            - ./:/var/www
        ports:
            - 80
        depends_on:
            - practica-php
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOSTS}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOSTS}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        networks:
            - nginx-proxy
            - practica

    practica-php:
        container_name: practica-php
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - practica-mysql
            - practica-redis
        ports:
            - 9000
        networks:
            - practica

    practica-mysql:
        container_name: practica-mysql
        build:
            context: ./
            dockerfile: docker/mysql/Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_EXTERNAL_PORT}:3306
        networks:
            - practica

    practica-redis:
        container_name: practica-redis
        build:
            args:
                REDIS_PASSWORD: ${REDIS_PASSWORD}
            context: ./
            dockerfile: docker/redis/Dockerfile
        ports:
            - 6379
        sysctls:
            - net.core.somaxconn=511
        networks:
            - practica

networks:
    practica:
    nginx-proxy:
        external: true
